@startuml
skinparam backgroundColor #EEEBDC
skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF}

autonumber 1 1 "<b>[00]"
group Payment Service
    group GET /payments/credit-transfers
        api -> paymentService: GET /payments/credit-transfers
        database    paymentDb    as paymentDb
        paymentService -> paymentDbDb: findAllCreditTransfers()
        api <-[#green]- paymentService: 200 OK
    end
    group GET /transactions/{id}
        api -> paymentService: GET /transactions/{id}
        paymentService -> transactionDb: findTransactionById()
        api <-[#green]- paymentService: 200 OK
        api <-[#red]- paymentService: 404 Not Found
    end
    group POST /payments/credit-transfer
           api -> paymentService: POST /payments/credit-transfer
            paymentService -> accountService: getAccountById()
            accountService -> accountDb: findAccountById()
            accountService --> paymentService: Account
            paymentService -> transactionDb: saveTransaction()
            api <-[#green]- paymentService: 201 Created
    end
    group PUT /transactions/{id}
        api -> paymentService: PUT /transactions/{id}
        paymentService -> transactionDb: updateTransaction()
        api <-[#green]- paymentService: 200 OK
        api <-[#red]- paymentService: 404 Not Found
    end
end
@enduml